---
title: "Parallel rqdatatable"
author: "John Mount"
date: "`r Sys.Date()`"
output: github_document
---

One can try to execute `relop` trees in parallel. However, in unless the pipeline is very expensive
the overhead of partitioning and distributing the work will by far overwhelm any parallel speedup.
Also `data.table` itself already seems to exploit some thread-level parallelism (notice user time > elapsed time).

```{r setup}
have_parallel <- requireNamespace("parallel", quietly = TRUE)
```

```{r ex, eval=have_parallel}
library("rqdatatable")
library("microbenchmark")
library("WVPlots")

cl <- parallel::makeCluster(4)
#parallel::clusterEvalQ(cl, library("rquery"))
#parallel::clusterEvalQ(cl, library("rqdatatable"))

set.seed(2362)
mk_example <- function(nkey, nrep, ngroup = 20) {
  keys <- paste0("key_", seq_len(nkey))
  key_group <- sample(as.character(seq_len(ngroup)), 
                      length(keys), replace = TRUE)
  names(key_group) <- keys
  key_table <- data.frame(
    key = rep(keys, nrep),
    stringsAsFactors = FALSE)
  key_table$data <- runif(nrow(key_table))
  instance_table <- data.frame(
    key = rep(keys, nrep),
    stringsAsFactors = FALSE)
  instance_table$id <- seq_len(nrow(instance_table))
  instance_table$info <- runif(nrow(instance_table))
  # groups should be no finer than keys
  key_table$key_group <- key_group[key_table$key]
  instance_table$key_group <- key_group[instance_table$key]
  list(key_table = key_table,
       instance_table = instance_table)
}

dlist <- mk_example(10, 5)
data <- dlist$instance_table
annotation <- dlist$key_table


# possible data lookup: find rows that
# have lookup data <= info
optree <- local_td(data) %.>%
  natural_join(., local_td(annotation), jointype = "INNER", by = "key") %.>%
  select_rows_nse(., data <= info) %.>%
  pick_top_k(., 
             k = 1,
             partitionby = "id",
             orderby = "data",
             reverse = "data",
             keep_order_column = FALSE) %.>%
  orderby(., "id")
cat(format(optree))

                   

res1 <- ex_data_table(optree)
head(res1)
nrow(res1)

res2 <- ex_data_table_parallel(optree, "key_group", cl)
head(res2)
nrow(res2)

dlist <- mk_example(100, 1000)
data <- dlist$instance_table
annotation <- dlist$key_table

timings <- microbenchmark(
  ex_data_table(optree),
  ex_data_table_parallel(optree, "key_group", cl),
  times = 5L)

print(timings)

timings <- as.data.frame(timings)
timings$seconds <- timings$time/1e+9
ScatterBoxPlotH(timings, xvar = "seconds", yvar = "expr", 
                title="task time by method")

parallel::stopCluster(cl)
rm(list = "cl")
```
